#!/usr/bin/env python3
"""
make_course_file -- build a course file (driving line + sections) for
course_supervisor from a recorded keyframe trajectory.

The driving line is the keyframe path (loop_pgo pose format:
'<name> x y z qw qx qy qz' per line, in the map frame the robot localizes in),
densified to --resolution and lightly smoothed. Section starts are given in a
template either by keyframe index ('start_kf', fractional allowed) or by a map
position ('start_xy', projected onto the line after the previous section).

Template format:
  end_kf: 164                       # optional, default: last keyframe
  sections:
    - {name: start_lane, start_kf: 0, mode: nav2, lidar: true}
    - {name: ramp, start_kf: 5.1, mode: path_tracker, lidar: false, speed: 0.30}
    - {name: top, start_xy: [5.2, -10.1], mode: nav2}
    ...
Any other section keys (speed, trigger_tag, trigger_range) are copied as-is.

Usage:
  ros2 run course_supervisor make_course_file --poses poses_fixed_v2.txt \\
      --template config/obstacle_course_template.yaml --output config/obstacle_course.yaml
"""
import argparse
import math
import sys

import numpy as np
import yaml


def read_xy(path):
    pts = []
    with open(path) as f:
        for line in f:
            parts = line.split()
            if len(parts) == 8:
                pts.append([float(parts[1]), float(parts[2])])
    return np.array(pts)


def densify(xy, res):
    seg = np.diff(xy, axis=0)
    s = np.r_[0.0, np.cumsum(np.hypot(seg[:, 0], seg[:, 1]))]
    sd = np.arange(0.0, s[-1], res)
    sd = np.r_[sd, s[-1]]
    return np.c_[np.interp(sd, s, xy[:, 0]), np.interp(sd, s, xy[:, 1])], s


def smooth(xy, res, sigma_m):
    if sigma_m <= 0:
        return xy
    half = int(math.ceil(3 * sigma_m / res))
    k = np.exp(-0.5 * (np.arange(-half, half + 1) * res / sigma_m) ** 2)
    k /= k.sum()
    pad = np.vstack([np.repeat(xy[:1], half, 0), xy, np.repeat(xy[-1:], half, 0)])
    out = np.c_[np.convolve(pad[:, 0], k, 'valid'), np.convolve(pad[:, 1], k, 'valid')]
    out[0], out[-1] = xy[0], xy[-1]
    return out


def arclength(xy):
    seg = np.diff(xy, axis=0)
    return np.r_[0.0, np.cumsum(np.hypot(seg[:, 0], seg[:, 1]))]


def project(xy, s, p, s_lo, s_hi):
    m = (s >= s_lo) & (s <= s_hi)
    idx = np.flatnonzero(m)
    if idx.size == 0:
        raise ValueError(f'no path points between s={s_lo:.2f} and s={s_hi:.2f}')
    d = np.hypot(xy[idx, 0] - p[0], xy[idx, 1] - p[1])
    k = idx[int(np.argmin(d))]
    return float(s[k]), float(d.min())


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--poses', required=True)
    ap.add_argument('--template', required=True)
    ap.add_argument('--output', required=True)
    ap.add_argument('--resolution', type=float, default=0.05)
    ap.add_argument('--smooth-sigma', type=float, default=0.15, help='Smoothing along the line (m).')
    ap.add_argument('--frame-id', default='map')
    a = ap.parse_args()

    with open(a.template) as f:
        tpl = yaml.safe_load(f)
    kf = read_xy(a.poses)
    end_kf = float(tpl.get('end_kf', len(kf) - 1))

    def kf_xy(k):
        i = int(min(max(math.floor(k), 0), len(kf) - 2))
        t = k - i
        return kf[i] * (1 - t) + kf[i + 1] * t

    n_end = int(math.floor(end_kf))
    line = np.vstack([kf[:n_end + 1], [kf_xy(end_kf)]]) if end_kf > n_end else kf[:n_end + 1]
    dense, s_kf = densify(line, a.resolution)
    dense = smooth(dense, a.resolution, a.smooth_sigma)
    s = arclength(dense)

    sections, prev = [], 0.0
    for sec in tpl['sections']:
        out = {k: v for k, v in sec.items() if k not in ('start_kf', 'start_xy')}
        if 'start_kf' in sec:
            k = float(sec['start_kf'])
            approx = float(np.interp(k, np.arange(len(s_kf)), s_kf))
            s0, d = project(dense, s, kf_xy(k), approx - 1.0, approx + 1.0)
        elif 'start_xy' in sec:
            s0, d = project(dense, s, sec['start_xy'], prev, prev + 40.0)
        else:
            sys.exit(f"section {sec['name']}: needs start_kf or start_xy")
        if d > 0.5:
            print(f"WARNING: section {sec['name']} anchor is {d:.2f} m from the driving line")
        s0 = max(s0, prev)
        out['s_start'] = round(s0, 3)
        sections.append(out)
        prev = s0
    if sections:
        sections[0]['s_start'] = 0.0

    with open(a.output, 'w') as f:
        f.write('# Generated by make_course_file -- edit the template and regenerate rather than\n')
        f.write('# editing the path by hand. Section s_start = metres along the driving line.\n')
        yaml.safe_dump({'frame_id': a.frame_id, 'length_m': round(float(s[-1]), 3)}, f, sort_keys=False)
        f.write('sections:\n')
        for sec in sections:
            f.write('  - ' + yaml.safe_dump(sec, default_flow_style=True, sort_keys=False, width=1000).strip() + '\n')
        f.write('path:\n')
        for x, y in dense:
            f.write(f'  - [{x:.3f}, {y:.3f}]\n')
    print(f'wrote {a.output}: {len(dense)} points, {s[-1]:.2f} m, {len(sections)} sections')
    for sec in sections:
        print(f"  s={sec['s_start']:6.2f}  {sec['name']:28s} mode={sec.get('mode', 'nav2'):13s} lidar={sec.get('lidar', True)}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
